language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r devsite/requirements.txt
  - pip install pytest-cov

# command to run tests
script:
  - py.test --cov=./
  - bash <(curl -s https://codecov.io/bash)
